### ISSUE TITLE
test party bug - Geocoding failed for origin: ZERO_RESULTS (Routing doesn't work)

### ISSUE THREAD

**Issue by KartikeySharma** [gcivil-nyu-org/wed-fall24-team4#164]
**Note: I have tested this out, and I don't think its a text or geocoding issue.**

### Issue:
Adding a Start Location and End Location of 103 St and 8 St NYU  leads to the following alert message **_"Geocoding failed for origin: ZERO_RESULTS"_**

- Also, 103 St is a VALID subway station (the route shows for 103 St and 8 St NYU not when you enter them as text but when you follow a particular flow -> Recording 2 for reference)

### Steps to Reproduce:
1. Login / Don't Log In
2. Allow Location Access (visible in recording)
3. Enter 103 St and 8 St NYU as the Start and End Location respectively.
4. Click Find Route, the error should pop up.

### Where is the error being triggered:
`console.log("Geocoding failed for origin:", status)` in map.html -> [Link to Exact Line on Github Repo](https://github.com/gcivil-nyu-org/wed-fall24-team4/blob/develop/maps/templates/map.html#L472)

### Recording:
- [Not Working and Error Pops Up](https://drive.google.com/file/d/1UFD36jBth2-bzveDvHHgTQiNCn9tOwnR/view?usp=sharing)
- [Particular Flow that allows to search using 103 St itself](https://drive.google.com/file/d/1keSnz6ZS5dfqs6DyI2KGghlfUck67GVz/view?usp=sharing)

### Screenshot:
(Start is `103 St` and End Location is `8 St NYU` -> will be visible in recording though)
![image](https://github.com/user-attachments/assets/306d3f34-2a74-4db7-8b23-34449e43c8c0)

### Note: This is not mentioned in the testing doc as of 11/13/2024 at 8:47 PM

**Comment by seanpanpan321** [comment]
This behavior is expected because manually entering ‘103 St’ can reference multiple locations, such as various street addresses or different subway station entrances (there are 3). This ambiguity is similar to entering a name like ‘Trader Joe’s,’ which can result in a ‘Geocoding failed for origin: ZERO_RESULTS’ error if the system cannot pinpoint the specific Trader Joe’s that the user is referencing. However, when the subway station is selected from a list, the app uses a specific geolocation, making it identifiable.

However, we agree that it might be confusing for the end user, as it appears the same text input produces different results. We will try to give visual hints so it is clearer.

**Comment by KartikeySharma** [comment]
So how about we choose any one (of those 3) or notify the user that there are 3 103St subway stations? Maybe some form of user  aide could be helpful.

Maybe a better alert message saying that "There are 'n' 103 St stations in NYC"?
